Exercise 1) Create an array of integers from 0 to 20 with steps of 2.

    - Create 1D array starting at 0, ending at 20, counting in steps of 2



In [3]:
import numpy as np

my_array = np.arange(0,21,2)
print(my_array)

[ 0  2  4  6  8 10 12 14 16 18 20]


Exercise 2) Create an array of 5 random floats between 0 an 1

    - Generate an array with 5 random float values between 0 and 1.
    - Use { np.random.rand(size) } to generate random numbers between 0 and 1

In [5]:
import numpy as np

random_array = np.random.rand(5)
print(random_array)

[0.65684542 0.58414998 0.25292854 0.25958889 0.53637204]


Exercise 3) Create a 3x3 indentify matrix.

    - Create a square matrix where diagonal elements are 1 and others are 0.
    - use np.eye(size) for identify matrices.

In [6]:
import numpy as np

matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Exercise 4) Create a 4x4 with random intengers between 1 and 100.

    - Generate random integers in matrix form.
    - Use 'np.random.randint(low, high, size =(rows, columns))

In [12]:
matrix = np.random.randint(1, 101, size =(4,4))
print(matrix)

[[ 42   3  55  18]
 [ 25  71 100  99]
 [ 96  65  66   2]
 [ 84  65  23 100]]


Exercise 5) Reshape a 1D array of numbers from 1 and 12 into 3x4 matrix.

    - Creats numbers and reshape them.
    - Use 'np.arange( , )' and 'np.reshape()'

In [ ]:
import numpy as np

array_1D = np.arange(1,13)
array_matrix = array_1D.reshape(3,4)    # We don't use 'np.' , because you use np before to create np.arange()

print(array_matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Exercise 6) Find the sum of all elements in a 3x3 random integer matrix

    - Geneate a random matrix and sum all values.
    - Use np.sum( ) agter generating the array.

In [19]:
import numpy as np

matrix = np.random.randint(0,11, size=(3,3))
print(matrix)

print("Sum: ", matrix.sum())

[[8 0 5]
 [0 9 0]
 [2 7 3]]
Sum:  34


Exercise 7) Find the mean of a 1D array of number from 1 to 100.

    - Calculate the average.
    - Use np.mean()

In [ ]:
import numpy as np

array_100 = np.arange(1,101)
array_mean = array_100.mean()

print("The mean of the array is:",array_mean)

The mean of the array is: 50.5


Exercise 8) Create two arrays and multiply them element-wise.

    - Multiply two arrays of the same size.
    - Use * operator to multiply arrays element by element.

In [24]:
import numpy as np

a = np.array([2,3,4])
b = np.array([5,4,5])

result = a * b

print(result)

[10 12 20]


Exercise 9) Reverse a 1D array of number from 1 to 10

    - Flip the array backwards.
    - Use slicing with [::-1]

In [26]:
import numpy as np

arr = np.arange(1,11)
print(arr)

reverse = arr[::-1]

print(f"Reverse numbers: {reverse}")

[ 1  2  3  4  5  6  7  8  9 10]
Reverse numbers: [10  9  8  7  6  5  4  3  2  1]


Exercise 10) Create a 1D array and find its standard deviation.

    - Find the standard deviation (spread of data).
    - Use .std() method.

In [27]:
import numpy as np

arr = np.array([1, 2, 4, 5])
print(arr)

stand_devi= arr.std()
print(stand_devi)

[1 2 4 5]
1.5811388300841898
