array.reshape(new_shape)

    - changes the shape of an array without changing its data.

In [7]:
import numpy as np

arr = np.arange(1,10)
print(arr)

reshaped = arr.reshape(3,3)
print(reshaped)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Sum()

    - Returns the sum of all elements.

In [9]:
import numpy as np

arr = np.arange(1,5)
print(arr)

suma = arr.sum()
print(suma)

[1 2 3 4]
10


Max() and Min()

    - Finds the largest or smallest number in the array.

In [23]:
import numpy as np

arr = np.random.randint(1,20, size =(10))
print(arr)

print(arr.max())
print(arr.min())

[18  8 16 13 13  4  9  8  2 13]
18
2


Mean() -> Avg

    - Calculate the average value of the array.

In [24]:
import numpy as np

arr = np.array([1,3,4,22,5])
print(arr)

mean_avg = arr.mean()
print(mean_avg)

[ 1  3  4 22  5]
7.0


Standart Deviation -> .std()

    - Tells you how spread out the numbers are.

In [25]:
import numpy as np

standar_desviation = np.array([100,2,23,11,70,25,70])
print(standar_desviation)

avg = standar_desviation.std()
print(avg)


[100   2  23  11  70  25  70]
34.09231165945944


Flatten -> .flatten()

    - Turns a multi-dimensional array into a 1D array

In [27]:
import numpy as np 

matrix = np.array([[1,2,4], [5,5,5]])
print(matrix)

flatten = matrix.flatten()
print(flatten)

[[1 2 4]
 [5 5 5]]
[1 2 4 5 5 5]


Transpose -> .T

    - Swaps rows and columns (matrix transpose)

In [29]:
import numpy as np

matrix = np.array([[1,3,4], [2,3,4]])
print(matrix)

transpose = matrix.T
print(transpose)

[[1 3 4]
 [2 3 4]]
[[1 2]
 [3 3]
 [4 4]]


Sort -> .sort()

    - Sorts the array in ascending order (in-place)
    - you don't need to create a new variable, only apply

In [ ]:
import numpy as np

arr = np.array([[1,8,3,9,5,6], [43,22,13,94,55,36,]])
print(arr)

arr.sort() # you don't need to create a new variable, only apply
print(arr)

[[ 1  8  3  9  5  6]
 [43 22 13 94 55 36]]
[[ 1  3  5  6  8  9]
 [13 22 36 43 55 94]]


Copy -> .copy()

    - Creates a copy of the array (important if you wan to modify without changing the original)

In [34]:
import numpy as np

a = np.array([1,2,3,4])

b = a.copy()

print(a,b)

[1 2 3 4] [1 2 3 4]


Argmax-> .argmax() and Argmin -> .argmin()

    - Gives the index of the largest/smallest values

In [ ]:
import numpy as np

ar = np.array([0,1,2,3,4,5,7])

print(ar.argmax()) # index: 0
print(ar.min())    # index: 6

6
0
